import os
import logging
import re
from datetime import datetime
from typing import Dict, Any, List, Optional
from app.core.config import settings

logger = logging.getLogger(__name__)

class ObsidianService:
    """Service for managing Technical Memory in Obsidian."""

    def __init__(self):
        # Default to /tmp/obsidian for ephemeral production storage if not set
        self.vault_path = settings.OBSIDIAN_VAULT_PATH or "/tmp/obsidian"
        
        try:
            os.makedirs(self.vault_path, exist_ok=True)
            logger.info(f"Obsidian vault initialized at: {self.vault_path}")
        except Exception as e:
            logger.error(f"Failed to initialize Obsidian vault at {self.vault_path}: {e}")
            self.vault_path = None

    def save_analysis(self, symbol: str, analysis: Dict[str, Any]):
        """Save an enriched market analysis to a markdown file in Obsidian."""
        if not self.vault_path or not os.path.exists(self.vault_path):
            return

        date_str = datetime.now().strftime("%Y-%m-%d")
        time_str = datetime.now().strftime("%H-%M")
        folder_path = os.path.join(self.vault_path, "NuoTrading", "Analysis", symbol)
        
        # Ensure folders exist
        os.makedirs(folder_path, exist_ok=True)

        filename = f"{date_str}-{time_str}-{symbol}-Analysis.md"
        file_path = os.path.join(folder_path, filename)

        # Extraction of key levels and patterns (if provided in analysis)
        levels = analysis.get('key_levels', ["S: No detectado", "R: No detectado"])
        patterns = analysis.get('patterns', ["Consolidación"])
        tags = analysis.get('tags', ["#analysis", "#ai-verdict"])
        
        # Prepend requested tags
        symbol_tag = f"#{symbol.lower()}"
        if symbol_tag not in tags: tags.append(symbol_tag)
        if "#nuotrading" not in tags: tags.append("#nuotrading")

        # Build markdown content with the new structure
        content = f"""---
type: technical-analysis
symbol: {symbol}
date: {datetime.now().isoformat()}
recommendation: {analysis.get('recommendation')}
confidence: {analysis.get('confidence')}%
sentiment: {analysis.get('sentiment')}
---

# Analysis for {symbol} - {date_str} {time_str}

## AI Insights
> [!info] Reasoning
> {analysis.get('reasoning')}

## Market Memory (Obsidian++)
### 📈 Key Levels
{chr(10).join([f"- **{lvl}**" for lvl in levels])}

### 🔍 Historical Patterns
- **Pattern**: {patterns[0] if patterns else "None"}
- **Confidence**: {analysis.get('confidence')}%

### 🏷️ Tags
{' '.join(tags)}

---
## Technical Context
- **RSI**: {analysis.get('technical_context', {}).get('rsi', 'N/A')}
- **Price**: ${analysis.get('technical_context', {}).get('price', 'N/A')}

*This analysis was automatically generated by NuoTrading AI Orchestrator (Phase 3).*
"""

        try:
            with open(file_path, "w", encoding="utf-8") as f:
                f.write(content)
            logger.info(f"Technical memory saved to Obsidian: {file_path}")
        except Exception as e:
            logger.error(f"Error saving technical memory to Obsidian: {e}")

    def get_memory(self, symbol: str, limit: int = 5) -> List[Dict[str, Any]]:
        """Retrieve the last N analyses for a symbol from Obsidian."""
        if not self.vault_path or not os.path.exists(self.vault_path):
            return []

        folder_path = os.path.join(self.vault_path, "NuoTrading", "Analysis", symbol.upper())
        if not os.path.exists(folder_path):
            return []

        files = [f for f in os.listdir(folder_path) if f.endswith(".md")]
        files.sort(reverse=True) # Last ones first
        
        memories = []
        for filename in files[:limit]:
            file_path = os.path.join(folder_path, filename)
            try:
                with open(file_path, "r", encoding="utf-8") as f:
                    content = f.read()
                    
                    # Basic parser for reasoning and metadata
                    reasoning_match = re.search(r"> Reasoning\s*> (.*)", content)
                    reasoning = reasoning_match.group(1) if reasoning_match else "No reasoning found."
                    
                    # Extract metadata from frontmatter
                    rec_match = re.search(r"recommendation: (.*)", content)
                    conf_match = re.search(r"confidence: (.*)%", content)
                    
                    memories.append({
                        "filename": filename,
                        "recommendation": rec_match.group(1) if rec_match else "N/A",
                        "confidence": conf_match.group(1) if conf_match else "0",
                        "reasoning": reasoning,
                        "date": filename[:10]
                    })
            except Exception as e:
                logger.error(f"Error reading obsidian file {filename}: {e}")
                
        return memories
